---
# Travis Config to deploy Ansible to the servers

language: java
jdk: oraclejdk8

# Send build status to year4000 irc channel
notifications:
  irc:
    channels:
      - "irc.esper.net#year4000"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    use_notice: true
    skip_join: true

# Compile the project
script: ./gradlew
