language: java
jdk:
  - oraclejdk8
notifications:
  email: false
before_install:
  - git config user.email "year4000@year4000.net"
  - git config user.name "Year4000"
  - git clone https://github.com/Year4000/FireCast.git ; cd FireCast/ ; ./init.sh ; ./build.sh ; cd ../
  - git submodule update --init --recursive
  - cd utilities/ ; mvn clean install ; cd ../
install:
  - mvn clean install -o
