language: java
jdk:
  - oraclejdk8
notifications:
  email: false
before_install:
  - ./before.sh
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success:
  - ./deploy.sh
