language: java
jdk:
  - oraclejdk8
notifications:
  email: false
before_install:
  - git config --global user.email "year4000@year4000.net"
  - git config --global user.name "Year4000"
  - git clone https://github.com/Year4000/FireCast.git ; cd FireCast/ ; ./init.sh ; ./build.sh ; cd ../
  - git clone https://github.com/Year4000/Utilities.git ; cd Utilities/ ; mvn clean install ; cd ../
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success:
  - cp ./target/MapNodes.jar ./Games/plugins/MapNodes.jar
  - cd ./Games/
  - git add ./plugins/MapNodes.jar
  - git commit -m "Update MapNodes to $(git log --pretty=format:'%h' -1)"
  - git push origin master