language: java
jdk:
  - oraclejdk8
notifications:
  email: false
before_install:
  - git clone https://github.com/Year4000/FireCast.git ; cd FireCast/ ; ./init.sh ; ./build.sh ; cd ../
  - git submodule update --init --recursive
  - cd utilities/ ; mvn clean install ; cd ../
