---
# Build the docker image for the various mapnodes configurations

version: '2'

services:
  mapnodes:
    build: sponge/
    image: year4000/mapnodes:spongevanilla
    ports:
      - "25565:25565"
    volumes:
      - ./sponge/build/libs/mapnodes-3.0.0-all.jar:/opt/year4000/minecraft/mods/mapnodes.jar
      - ./run/maps:/opt/year4000/minecraft/maps
      - ./run/logs:/opt/year4000/minecraft/logs
  bridge:
    build: ./
    image: year4000/mapnodes:bridge
    # volumes:
    #   - ./run/bridge:/opt/mapnodes/bridge/.gradle/v8/out.gn/x64.release/
    