---
# Build the docker image for the various mapnodes configurations

version: '2'

services:
  spongevanilla:
    build: sponge/
    image: year4000/mapnodes:spongevanilla
    ports:
      - "25565:25565"
    volumes:
      - ./sponge/build/libs/mapnodes-3.0.0-all.jar:/opt/year4000/minecraft/mods/mapnodes.jar
      - ./run/sponge-server/maps:/opt/year4000/minecraft/maps

