---
# Build the docker image for the various mapnodes configurations

version: '2'

services:
  spongevanilla:
    build: sponge/
    image: year4000/mapnodes:spongevanilla
    ports:
      - "25565:25565"
    volumes:
      - ./run/sponge-server/mods:/opt/year4000/minecraft/mods
      - ./run/sponge-server/maps:/opt/year4000/minecraft/maps

