#! /usr/bin/python

URL = 'https://raw.githubusercontent.com/Year4000/Tasks/master/src/tasks.py'

if __name__ == '__main__':
    import os

    file_name = '.tasks.py'

    if not os.path.isfile(file_name):
        os.system('wget -O - {} > {}'.format(URL, file_name))

    with open(file_name) as file_task:
        exec(''.join(file_task.readlines()))
