name: ${pom.name}
author: Year4000
version: ${pom.version}-git-${git.commit.id.abbrev}
description: ${git.commit.message.short}
main: ${pom.groupId}.${pom.artifactId}.${pom.name}Plugin
depend: [Utilities]
