/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_year4000_mapnodes_v8_V8Engine */

#ifndef _Included_net_year4000_mapnodes_v8_V8Engine
#define _Included_net_year4000_mapnodes_v8_V8Engine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_year4000_mapnodes_v8_V8Engine
 * Method:    startVm
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_year4000_mapnodes_v8_V8Engine_startVm(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
