name: Docker

# Only deploy changes to selected branch(es)
on:
  push:
    branches:
    - 'master'
    - 'feature/v8'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Docker
      run: ./gradlew test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Docker
      run: ./gradlew buildDocker
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ewized/mapnodes/spongevanilla
        username: ewized
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
